### ISSUE TITLE
Migrate to me.maciejb.etcd-client

### ISSUE THREAD

**Issue by rkrzewski** [rkrzewski/akka-cluster-etcd#51]
Etcd-client was extracted to separate project https://github.com/maciej/etcd-client that is now published to Maven Central: [me.maciejb.etcd-client](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22me.maciejb.etcd-client%22)
A few cleanups are in order:
- [x] add dependency to sbt project
- [x] remove etcd-client sources from this repository
- [ ] update docs
- [ ] migrate outstanding issues
